version: "3.9" 
services:
  nginx:
    image: nginx
    ports:
      - "9091:80"
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      -  ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/apache2/.htpasswd
    networks:
        - hdhomerun
  api:
    build: .
    volumes:
      - ./static/live:/live
      - ./cache:/cache
    ports:
      - "9092:8000"
    networks:
      - hdhomerun
    environment:
      - TV_MEDIA_API_KEY=${TV_MEDIA_API_KEY}

networks:
  hdhomerun:
  