name: Docker Image CI

on:
  push:
  
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: setup IMAGE_TAG env var
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: "therumbler/channels:${{ env.IMAGE_TAG }}"
          build-args: |
            IMAGE_TAG=${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
