name: Docker Image CI

on:
  push:
  
jobs:

  buildx:

    runs-on: ubuntu-latest
    env:
      GITHUB_SHA: ${GITHUB_SHA}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: "therumbler/channels:${{env.GITHUB_SHA}}"
      
