name: Docker Image CI

on:
  push:
  
jobs:

  buildx:

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: "therumbler/channels:${{ env.TAG }}"
          build-args: |
            TAG=${{ env.GITHUB_SHA }}
